/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.SalesEvent
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object InputApi {

  /**
   * Adds an event to the system
   * 
   * Expected answers:
   *   code 201 :  (event created)
   *   code 400 :  (invalid input, object invalid)
   *   code 409 :  (an existing event already exists)
   * 
   * @param event Event to add
   */
  def addEvent(event: Option[SalesEvent] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/yuanzhao/sales_prediction/1.0.0", "/ingest", "application/json")
      .withBody(event)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](409)
        /**
   * uploads an event dump file
   * 
   * Expected answers:
   *   code 200 :  (OK)
   */
  def ingestPut(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, "https://virtserver.swaggerhub.com/yuanzhao/sales_prediction/1.0.0", "/ingest", "application/json")
      .withSuccessResponse[Unit](200)
      

}

