/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object OutputApi {

  /**
   * By passing in the appropriate options, you can get predicted item sold for a SKU / Good 
   * 
   * Expected answers:
   *   code 200 : Any (prediction result)
   *   code 400 :  (bad input parameter)
   * 
   * @param goodsId 
   * @param skuId 
   * @param ndays predict the sales n days out
   */
  def prediction(goodsId: String, skuId: String, ndays: Option[Int] = None): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.GET, "https://virtserver.swaggerhub.com/yuanzhao/sales_prediction/1.0.0", "/predict", "application/json")
      .withQueryParam("goods_id", goodsId)
      .withQueryParam("sku_id", skuId)
      .withQueryParam("ndays", ndays)
      .withSuccessResponse[Any](200)
      .withErrorResponse[Unit](400)
      

}

