/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class SalesEvent (
  /* Event UNIX timestamp */
  ts: Long,
  /* Event SKU Id */
  skuId: Int,
  /* Event Goods Id */
  goodsId: Int,
  categoryName: String,
  subCategoryName: String,
  shopPrice: Float,
  prstPrice: Float,
  /* Customer origination country */
  country: String,
  itemSold: Int,
  uniqueBuyers: Int,
  clicks: Int,
  salesAmount: Int
) extends ApiModel


